name: comment_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11.*
  - click=8.1.7
  - nltk
  - pandas=2.1.2
  - nlpaug
  - altair=5.1.2
  - scikit-learn=1.3.2
  - lightgbm
  - joblib
  - myst-nb
  - jupyter-book
